package com.customminecraftserver.session;

public enum SessionState {
    CONNECTED,
    JAVA_HANDSHAKE,
    JAVA_STATUS,
    JAVA_LOGIN,
    JAVA_ENCRYPTION_NEGOTIATION,
    JAVA_AUTHENTICATING,
    JAVA_WAITING_LOGIN_ACK,
    JAVA_CONFIGURING,
    JAVA_PLAY,
    JAVA_WAITING_SETTINGS,
    JAVA_WAITING_PONG,
    JAVA_TERMINATED,
    BEDROCK_UNCONNECTED,
    BEDROCK_OPEN_CONNECTION,
    BEDROCK_CONNECTED,
    BEDROCK_LOGIN,
    BEDROCK_AUTHENTICATING,
    BEDROCK_SECURE_SESSION,
    BEDROCK_INITIALIZING,
    BEDROCK_WAITING_CHUNK_RADIUS,
    BEDROCK_WAITING_LOCAL_PLAYER_INITIALIZATION,
    DISCONNECTED
}
